name: Post to Bluesky
on:
  pull_request:
    types: [opened,synchronize,reopened]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 'debug'
        run: echo "${{github.event.pull_request}}"
  # call-workflow-passing-data:
  #   uses: zachurich/gh-actions/.github/workflows/pr-bluesky.yml@main
  #   with:
  #     post: "${{ github.event.pull_request.title }} -  ${{ github.event.pull_request.url }}"
  #   secrets: inherit
