name: Post to Bluesky
on:
  pull_request:
    branches:
      - main
      - master
jobs:
  call-workflow-passing-data:
    uses: zachurich/gh-actions/.github/workflows/pr-bluesky.yml@main
    with:
      post: "Hello world"
    secrets: inherit
